# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: gh-domino

builds:
  - id: gh-domino
    binary: gh-domino
    main: ./cmd/gh-domino/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    wrap_in_directory: false
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

snapshot:
  version_template: "SNAPSHOT-{{ .Commit }}"
