#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

PROGRAM_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

if test -f "${PROGRAM_ROOT}/dist/gh-domino"; then
  exec "${PROGRAM_ROOT}/dist/gh-domino" "$@"
  return
fi

OS=$(uname -s)
ARCH=$(uname -m)

case "${OS}" in
  Linux)
    OS=linux
    ;;
  Darwin)
    OS=darwin
    ;;
  *)
    OS=unknown
    exit 1
    ;;
esac

case "${ARCH}" in
  x86_64)
    ARCH=amd64
    ;;
  arm64)
    ARCH=arm64
    ;;
  *)
    ARCH=unknown
    exit 1
    ;;
esac

mkdir -p "${PROGRAM_ROOT}/dist"

if [[ "${OS}" == "unknown" || "${ARCH}" == "unknown" ]]; then
  # Unsupported OS or Architecture. Run the script with go instead.
  if ! command -v go >/dev/null; then
    echo "Go not found on the system" >&2
    exit 1
  fi

  (cd "${PROGRAM_ROOT}" && go build -o dist/gh-domino ./cmd/gh-domino)
  exec "${PROGRAM_ROOT}/dist/gh-domino" "$@"
else
  GH_DOMINO_VERSION="2.0.0"
  curl -sSL "https://github.com/134130/gh-domino/releases/download/v${GH_DOMINO_VERSION}/gh-domino-${GH_DOMINO_VERSION}-${OS}-${ARCH}.tar.gz" | tar -xz -C "${PROGRAM_ROOT}/dist" gh-domino
  exec "${PROGRAM_ROOT}/dist/gh-domino" "$@"
fi
