[tools]
go = '1.25'
golangci-lint = "latest"
goreleaser = "latest"

[tasks.release]
run = """
#!/usr/bin/env bash
set -eou pipefail

export GITHUB_TOKEN=$(gh auth token)

goreleaser
"""

[tasks.check]
run = """
#!/usr/bin/env bash
set -eou pipefail
go mod tidy
golangci-lint run ./...
"""

[tasks.fix]
run = """
#!/usr/bin/env bash
set -eou pipefail
go mod tidy
golangci-lint run --fix ./...
"""
